<a href="https://colab.research.google.com/github/sivsri/jovian/blob/main/numpy_operations_assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.full_like
function2 = np.append
function3 = np.linalg.det, np.linalg.inv
function4 = np.all, np.any
function5 = np.percentile

## Function 1 - np.full_like

Returns array with the shape of the given array

In [24]:
# Example 1 - working (change this)
a = [[1, 2], [3, 4]]

like = np.full_like(a, 5)
like

array([[5, 5],
       [5, 5]])

array 'like' has the shape of array 'a' and filled with value of 2nd parameter passed, related to np.full but instead of explicit shape it takes the shape of array passed to it

In [27]:
# Example 2 - working
like_0 = np.zeros_like(a)
like_0

array([[0, 0],
       [0, 0]])

In [28]:
like_1 = np.ones_like(a)
like_1

array([[1, 1],
       [1, 1]])

similarly, zeros and ones

## Function 2 - np.append

append values to the end of the array

In [30]:
# Example 1 - working
np.append([1, 2, 3], [4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

1st parameter is array and the 2nd is the values

In [37]:
# Example 2 - working
np.append([[1, 2, 3]], [[4, 5, 6], [7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

3rd parameter is for column axis, by default its row-wise

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
b = np.array([1,2,3])
np.append([[4, 5, 6], [7, 8, 9]], b, axis=0)

ValueError: ignored

for 2-D array the values passed to append should be 2 Dimension too else the above error happens

In [39]:
np.append([[4, 5, 6], [7, 8, 9]], [b], axis=0)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

the error's cleared after enclosing the array 'b' within an array itself.

## Function 3 - np.linalg.det, np.linalg.inv

determinant and inverse of a matrix

In [21]:
# Example 1 - working
c = np.array([[1, 2], [3, 4]])
np.linalg.det(c)

-2.0000000000000004

The determinant of 2-D array of [ [a, b], [c, d] ] is ad - bc

In [22]:
# Example 2 - working
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

The above result is inverse of matrix 'c'

linalg(linear algebra) is a sub-package of NumPy

## Function 4 - np.all, np.any

Returns True or False based on the elements present in an array

In [17]:
# Example 1 - working
np.all([3, 4, 5])

True

All the elements present in the array are truthy values, so the result is True

In [18]:
# Example 2 - working
np.all([0, 4, 5])

False

The first element in the array is falsy, all the elements should be truthy value

In [19]:
# Example 3 - np.any
np.any([0, 4, 5])

True

The result is True if any one truthy value in the array

In [20]:
np.any([0, 0, 0])

False

The result is False cause there is no truthy value in this above array, basically it check for any one truthy.

## Function 5 - np.percentile

It gives n-th percentile of the data

In [11]:
# Example 1 - working
e = np.array([[20, 14, 8], [6, 4, 2]])
e

array([[20, 14,  8],
       [ 6,  4,  2]])

In [12]:
np.percentile(e, 50)

7.0

Its giving the value of 50th percentile among the array data provided.

It sorts all the data in ascending and provides the value according to percentile given to it.

In [14]:
# Example 2 - working
np.percentile(e, 75, axis=0)

array([16.5, 11.5,  6.5])

In [15]:
np.percentile(e, 25, axis=1)

array([11.,  3.])

It also takes 3rd parameter, for row or col operations as axis.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
np.percentile(e, 150)

ValueError: ignored

As above, the error states ValueError: Percentiles should range from 0 and 100 not 150

Its used in statistical operations like when need to know about the percentile value of the data.

Also, there's one more similar kinda function 'np.quantile'. Its exactly same as percentile but it takes 'n-th quartile' from 0 to 1

example: np.quantile(e, 0.33)

## Conclusion

Gone through the documentation and got familiar with NumPy.

Up next, the pandas library.